In [4]:
import pandas as pd

a = pd.Series([1, 2, 3, 4, 5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
a = {
    "exp" : [5,10,15,20,25],
    "salary" : [1000,2000,3000,4000,5000]
}

b = pd.DataFrame(a)
b

   exp  salary
0    5    1000
1   10    2000
2   15    3000
3   20    4000
4   25    5000

In [7]:
b.head(2)

   exp  salary
0    5    1000
1   10    2000

In [8]:
b.tail(3)

   exp  salary
2   15    3000
3   20    4000
4   25    5000

In [9]:
b.shape

(5, 2)

In [10]:
b.info

<bound method DataFrame.info of    exp  salary
0    5    1000
1   10    2000
2   15    3000
3   20    4000
4   25    5000>

In [11]:
b.describe()

             exp      salary
count   5.000000     5.00000
mean   15.000000  3000.00000
std     7.905694  1581.13883
min     5.000000  1000.00000
25%    10.000000  2000.00000
50%    15.000000  3000.00000
75%    20.000000  4000.00000
max    25.000000  5000.00000

In [16]:
import pandas as pd

data = {

    "Name" : ["Ali", "Ahmed", "Ayesha", "Hassan", "Hina"],
    "Roll No" : [1000, 2000, 3000, 4000, 5000],
    "Math" : [80, 90, 70, 60, 50],
    "Science" : [70, 80, 90, 60, 50],
    "English" : [60, 70, 80, 90, 100]

}

results = pd.DataFrame(data)
results

     Name  Roll No  Math  Science  English
0     Ali     1000    80       70       60
1   Ahmed     2000    90       80       70
2  Ayesha     3000    70       90       80
3  Hassan     4000    60       60       90
4    Hina     5000    50       50      100

In [20]:
results.describe()

          Roll No       Math    Science     English
count     5.00000   5.000000   5.000000    5.000000
mean   3000.00000  70.000000  70.000000   80.000000
std    1581.13883  15.811388  15.811388   15.811388
min    1000.00000  50.000000  50.000000   60.000000
25%    2000.00000  60.000000  60.000000   70.000000
50%    3000.00000  70.000000  70.000000   80.000000
75%    4000.00000  80.000000  80.000000   90.000000
max    5000.00000  90.000000  90.000000  100.000000

In [25]:
results = pd.DataFrame(data)
print(results)
print(results.describe())
print("Top Math Scorer:", results.loc[results['Math'].idxmax(), 'Name'])

     Name  Roll No  Math  Science  English
0     Ali     1000    80       70       60
1   Ahmed     2000    90       80       70
2  Ayesha     3000    70       90       80
3  Hassan     4000    60       60       90
4    Hina     5000    50       50      100
          Roll No       Math    Science     English
count     5.00000   5.000000   5.000000    5.000000
mean   3000.00000  70.000000  70.000000   80.000000
std    1581.13883  15.811388  15.811388   15.811388
min    1000.00000  50.000000  50.000000   60.000000
25%    2000.00000  60.000000  60.000000   70.000000
50%    3000.00000  70.000000  70.000000   80.000000
75%    4000.00000  80.000000  80.000000   90.000000
max    5000.00000  90.000000  90.000000  100.000000
Top Math Scorer: Ahmed

In [26]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Roll No  5 non-null      int64
 2   Math     5 non-null      int64
 3   Science  5 non-null      int64
 4   English  5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [27]:
results.head(3)

     Name  Roll No  Math  Science  English
0     Ali     1000    80       70       60
1   Ahmed     2000    90       80       70
2  Ayesha     3000    70       90       80

In [28]:
results.tail(3)

     Name  Roll No  Math  Science  English
2  Ayesha     3000    70       90       80
3  Hassan     4000    60       60       90
4    Hina     5000    50       50      100

In [29]:
# read csv
results = pd.read_csv('student_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.csv'